<?php

namespace App\Models;

use App\Models\Base\BaseModel;

/**
 * Class BaseModel
 * @package App\Models\Base
 */
class Room extends BaseModel
{
    protected $table = 'rooms';
    protected $fillable = ['id','room_code','room_name','id_type','id_floor','price','number_count','has_register','note','del_flg'];


    public function __get($attribute)
    {
        //return parent::__get($key); // TODO: Change the autogenerated stub
    }

}
